name: Build armbian for BoughBoot-dev
run-name: Build armbian for BoughBoot-dev
on:
  workflow_dispatch:
    inputs:
      armbian_gh_repo:
        description: armbian buuild github repo
        required: true
        default: ArchemedIan/build
        type: string
      armbian_ref:
        description: armbian ref
        required: true
        default: BoughBoot
        type: string

jobs:
  build:
      name: Prepare and build armbian
      runs-on: ubuntu-latest
      steps:
          - name: Setup Ubuntu
            run: sudo apt update

          - name: Maximize build space
            uses: easimon/maximize-build-space@master
            with:
              root-reserve-mb: 512
              swap-size-mb: 1024
              remove-dotnet: 'true'
              overprovision-lvm: 'true'
              remove-android: 'true'
              remove-haskell: 'true'
              remove-codeql: 'true'
              remove-docker-images: 'true'
          - name: Checkout
            uses: actions/checkout@v3
            with:
              repository: ${{ inputs.armbian_gh_repo }}
              ref: ${{ inputs.armbian_ref }}

          - name: Build
            run: |
              version=1.0-dev
              rootdir=$(pwd)
              NewName=BoughBoot_$version
              chmod a+x userpatches/customize-image.sh
              ./compile.sh BOARD=orangepi5-plus BRANCH=legacy RELEASE=bookworm KERNEL_CONFIGURE=no CLEAN_LEVEL=alldebs,images,debs
              
          - name: Upload artifacts
            uses: actions/upload-artifact@v3
            with:
              name: ${{ inputs.armbian_ref }}_output
              path: output/
          
