name: Build BoughBoot-dev
run-name: Build BoughBoot-${{ inputs.bb_ver }}-dev
on:
  workflow_dispatch:
    inputs:
      bb_ver:
        description: version
        required: true
        default: "next"
        type: string
      armbian_gh_repo:
        description: armbian build github repo
        required: true
        default: armbian/build
        type: string
      armbian_ref:
        description: armbian ref
        required: true
        default: v23.11
        type: string
      uboot_repo:
        required: true
        type: choice
        description: u-boot git repo
        options: 
        - https://source.denx.de/u-boot/u-boot
        - custom_repo
      uboot_repo_custom:
        description: custom u-boot git repo
        required: false
        type: string
      uboot_ref:
        required: true
        type: choice
        description: u-boot ref
        options: 
        - v2024.01
        - v2023.10
        - master
        - custom_ref
      uboot_ref_custom:
        description: custom u-boot ref
        required: false
        type: string

jobs:
  build:
    name: ${{ matrix.boards.name }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        boards: 
          [
            {
              "name": "rk3588-orangepi-5-plus",
              "u-boot-defconfig": "orangepi-5-plus-rk3588_defconfig",
              "armbian_board": "orangepi5-plus",
              "armbian_imgname": "BoughBoot_*_Orangepi5-plus*.img",
            }
          ]

    steps:

      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 512
          swap-size-mb: 1024
          remove-dotnet: 'true'
          overprovision-lvm: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'
          remove-docker-images: 'true'
          

      - name: Toolchain
        run: |
          sudo apt-get update
          sudo apt-get install gcc-12 gcc-12-aarch64-linux-gnu python3-pyelftools confget parted

          sudo ln -sf cpp-12 /usr/bin/cpp
          sudo ln -sf gcc-12 /usr/bin/gcc
          sudo ln -sf gcc-ar-12 /usr/bin/gcc-ar
          sudo ln -sf gcc-nm-12 /usr/bin/gcc-nm
          sudo ln -sf gcc-ranlib-12 /usr/bin/gcc-ranlib
          sudo ln -sf gcov-12 /usr/bin/gcov
          sudo ln -sf gcov-dump-12 /usr/bin/gcov-dump
          sudo ln -sf gcov-tool-12 /usr/bin/gcov-tool

          sudo ln -sf aarch64-linux-gnu-cpp-12 /usr/bin/aarch64-linux-gnu-cpp
          sudo ln -sf aarch64-linux-gnu-gcc-12 /usr/bin/aarch64-linux-gnu-gcc
          sudo ln -sf aarch64-linux-gnu-gcc-ar-12 /usr/bin/aarch64-linux-gnu-gcc-ar
          sudo ln -sf aarch64-linux-gnu-gcc-nm-12 /usr/bin/aarch64-linux-gnu-gcc-nm
          sudo ln -sf aarch64-linux-gnu-gcc-ranlib-12 /usr/bin/aarch64-linux-gnu-gcc-ranlib
          sudo ln -sf aarch64-linux-gnu-gcov-12 /usr/bin/aarch64-linux-gnu-gcov
          sudo ln -sf aarch64-linux-gnu-gcov-dump-12 /usr/bin/aarch64-linux-gnu-gcov-dump
          sudo ln -sf aarch64-linux-gnu-gcov-tool-12 /usr/bin/aarch64-linux-gnu-gcov-tool

      - name: Checkout buildbb
        uses: actions/checkout@v3
        with:
          repository: ArchemedIan/build-bb
          ref: main
          path: build-bb

      - name: Checkout u-boot-boughboot
        uses: actions/checkout@v3
        with:
          repository: ArchemedIan/Opi5-u-boot-boughboot
          ref: main
          path: u-boot-boughboot
      
      - name: Checkout Armbian
        uses: actions/checkout@v3
        with:
          repository: ${{ inputs.armbian_gh_repo }}
          ref: ${{ inputs.armbian_ref }}
          path: armbian
              
      - name: Build u-boot - ${{ matrix.boards.u-boot-defconfig }}
        run: |
          cd u-boot-boughboot
          chmod a+x ./build.sh 
          ./build.sh "${{ inputs.uboot_ref }}" "${{ inputs.uboot_repo }}" "${{ matrix.boards.u-boot-defconfig }}" "${{ inputs.uboot_ref_custom }}" "${{ inputs.uboot_repo_custom}}" "${{ matrix.boards.name }}"
          cd ..

      - name: Build Armbian - ${{ matrix.boards.armbian_board }}
        run: |
          cp build-bb/build-bb.sh .
          chmod a+x ./build-bb.sh
          sudo ./build-bb.sh "${{ inputs.bb_ver }}" "${{ matrix.boards.armbian_board }}" "${{ matrix.boards.armbian_imgname }}" "${{ matrix.boards.name }}"

      - name: Upload BoughBoot-${{ inputs.bb_ver }}-${{ matrix.boards.name }}
        uses: actions/upload-artifact@v3
        with:
          name: BoughBoot-${{ inputs.bb_ver }}-${{ matrix.boards.name }}
          path: out/*.xz
