name: Build openwrt for BoughBoot-dev
run-name: Build openwrt for BoughBoot-dev
on:
  workflow_dispatch:
    inputs:
      openwrt_gh_repo:
        description: openwrt github repo
        required: true
        default: mj22226/openwrt
        type: string
      openwrt_ref:
        description: openwrt ref
        required: true
        default: linux-6.7
        type: string

jobs:
  build:
      name: Prepare and build rockchip-6.7 images
      runs-on: ubuntu-latest
      steps:
          - name: Setup Ubuntu
            run: |
              sudo apt update
              sudo apt install -y python3 python3-pip python3-ply python3-distutils python3-pyelftools libpython3-dev swig
          - name: Maximize build space
            uses: easimon/maximize-build-space@master
            with:
              root-reserve-mb: 512
              swap-size-mb: 1024
              remove-dotnet: 'true'
              overprovision-lvm: 'true'
              remove-android: 'true'
              remove-haskell: 'true'
              remove-codeql: 'true'
              remove-docker-images: 'true'
          - name: Checkout
            uses: actions/checkout@v3
            with:
              repository: ${{ inputs.openwrt_gh_repo }}
              ref: ${{ inputs.openwrt_ref }}

          - name: Build
            run: |
              ./scripts/feeds update -a
              ./scripts/feeds install -a
              cd feeds/luci

              wget https://gist.githubusercontent.com/mj22226/f6db007367a22a31f9cb1c109a032b45/raw/be368c4f1605f652a001d81548c3a3e14adf6cb7/luci-app-diskman.patch

              git apply luci-app-diskman.patch
              cd -
              cd  feeds/packages
              wget https://gist.githubusercontent.com/mj22226/351f11e66f08f06e37a985719a31ddb4/raw/b35ba7a3aac1949bd6bbeaad065a0a93dc3c34f0/01-cpu.patch

              git apply  01-cpu.patch

              cd -
              sed -i "70s/'0'/'1'/" feeds/luci/applications/luci-app-statistics/root/etc/config/luci_statistics
              sed -i "83s/'0'/'1'/" feeds/luci/applications/luci-app-statistics/root/etc/config/luci_statistics
              sed -i "194s/'0'/'1'/" feeds/luci/applications/luci-app-statistics/root/etc/config/luci_statistics
              sed -i "211s/'0'/'1'/" feeds/luci/applications/luci-app-statistics/root/etc/config/luci_statistics
              sed -i "13s/'1'/'0'/" feeds/packages/utils/dockerd/files/etc/config/dockerd

              ./scripts/feeds update -a
              ./scripts/feeds install -a -f
              cp .github/workflows/config.buildinfo .config
              make defconfig
              wget https://gist.githubusercontent.com/mj22226/8fe3f95119c0ea42794f8241042b60d5/raw/1e0cb3155a8df2fd36a18629f08c51d3c90ecff9/0001-local-key.patch
              git apply 0001-local-key.patch
              make download -j32
              rm 0001-local-key.patch
              make tools/install -j$(nproc)
              make toolchain/install -j$(nproc)
              make -j$(nproc) 'IGNORE_ERRORS=n m'
              rm -rf bin/targets/rockchip/armv8/packages
              echo "DATE=$(date +'%Y.%m.%d')" >> $GITHUB_ENV
              ls
              ls bin
              ls bin/targets
              ls bin/targets/rockchip
              ls bin/targets/rockchip/armv8
          - name: Upload artifacts
            uses: actions/upload-artifact@v3
            with:
              name: ${{ inputs.openwrt_ref }_buildinfo
              path: |
                bin/targets/rockchip/armv8/config.buildinfo
                bin/targets/rockchip/armv8/feeds.buildinfo
                bin/targets/rockchip/armv8/profiles.json
                bin/targets/rockchip/armv8/version.buildinfo
                bin/targets/rockchip/armv8/sha256sums
                bin/targets/rockchip/armv8/openwrt-rockchip-armv8.manifest
          - name: Upload artifacts
            uses: actions/upload-artifact@v3
            with:
              if-no-files-found: ignore
              name: ${{ inputs.openwrt_ref }_openwrt-rockchip-armv8-friendlyarm_nanopi-r2s-squashfs
              path: bin/targets/rockchip/armv8/openwrt-rockchip-armv8-friendlyarm_nanopi-r2s-squashfs-sysupgrade.img.gz
          - name: Upload artifacts
            uses: actions/upload-artifact@v3
            with:
              if-no-files-found: ignore
              name: ${{ inputs.openwrt_ref }_openwrt-rockchip-armv8-friendlyarm_nanopi-r4s-squashfs
              path: bin/targets/rockchip/armv8/openwrt-rockchip-armv8-friendlyarm_nanopi-r4s-squashfs-sysupgrade.img.gz
          - name: Upload artifacts
            uses: actions/upload-artifact@v3
            with:
              if-no-files-found: ignore
              name: ${{ inputs.openwrt_ref }_openwrt-rockchip-armv8-friendlyelec_nanopi-r5c-squashfs
              path: bin/targets/rockchip/armv8/openwrt-rockchip-armv8-friendlyelec_nanopi-r5c-squashfs-sysupgrade.img.gz
          - name: Upload artifacts
            uses: actions/upload-artifact@v3
            with:
              if-no-files-found: ignore
              name: ${{ inputs.openwrt_ref }_openwrt-rockchip-armv8-friendlyelec_nanopi-r5s-squashfs
              path: bin/targets/rockchip/armv8/openwrt-rockchip-armv8-friendlyelec_nanopi-r5s-squashfs-sysupgrade.img.gz
          - name: Upload artifacts
            uses: actions/upload-artifact@v3
            with:
              if-no-files-found: ignore
              name: ${{ inputs.openwrt_ref }_openwrt-rockchip-armv8-friendlyelec_nanopi-r6c-plus-squashfs
              path: bin/targets/rockchip/armv8/openwrt-rockchip-armv8-friendlyelec_nanopi-r6c-plus-squashfs-sysupgrade.img.gz
          - name: Upload artifacts
            uses: actions/upload-artifact@v3
            with:
              if-no-files-found: ignore
              name: ${{ inputs.openwrt_ref }_openwrt-rockchip-armv8-friendlyelec_nanopi-r6c-squashfs
              path: bin/targets/rockchip/armv8/openwrt-rockchip-armv8-friendlyelec_nanopi-r6c-squashfs-sysupgrade.img.gz
          - name: Upload artifacts
            uses: actions/upload-artifact@v3
            with:
              if-no-files-found: ignore
              name: ${{ inputs.openwrt_ref }_openwrt-rockchip-armv8-friendlyelec_nanopi-r6s-squashfs
              path: bin/targets/rockchip/armv8/openwrt-rockchip-armv8-friendlyelec_nanopi-r6s-squashfs-sysupgrade.img.gz
          - name: Upload artifacts
            uses: actions/upload-artifact@v3
            with:
              if-no-files-found: ignore
              name: ${{ inputs.openwrt_ref }_openwrt-rockchip-armv8-pine64_quartz64-a-squashfs
              path: bin/targets/rockchip/armv8/openwrt-rockchip-armv8-pine64_quartz64-a-squashfs-sysupgrade.img.gz
          - name: Upload artifacts
            uses: actions/upload-artifact@v3
            with:
              if-no-files-found: ignore
              name: ${{ inputs.openwrt_ref }_openwrt-rockchip-armv8-radxa_rock-3a-squashfs
              path: bin/targets/rockchip/armv8/openwrt-rockchip-armv8-radxa_rock-3a-squashfs-sysupgrade.img.gz
          - name: Upload artifacts
            uses: actions/upload-artifact@v3
            with:
              if-no-files-found: ignore
              name: ${{ inputs.openwrt_ref }_openwrt-rockchip-armv8-radxa_rock-pi-4-squashfs
              path: bin/targets/rockchip/armv8/openwrt-rockchip-armv8-radxa_rock-pi-4-squashfs-sysupgrade.img.gz
          - name: Upload artifacts
            uses: actions/upload-artifact@v3
            with:
              if-no-files-found: warn
              name: ${{ inputs.openwrt_ref }_openwrt-rockchip-armv8-xunlong_orangepi-5-plus-squashfs
              path: bin/targets/rockchip/armv8/openwrt-rockchip-armv8-xunlong_orangepi-5-plus-squashfs-sysupgrade.img.gz
          - name: Upload artifacts
            uses: actions/upload-artifact@v3
            with:
              if-no-files-found: ignore
              name: ${{ inputs.openwrt_ref }_openwrt-rockchip-armv8-friendlyarm_nanopi-r2s-ext4
              path: bin/targets/rockchip/armv8/openwrt-rockchip-armv8-friendlyarm_nanopi-r2s-ext4-sysupgrade.img.gz
          - name: Upload artifacts
            uses: actions/upload-artifact@v3
            with:
              if-no-files-found: ignore
              name: ${{ inputs.openwrt_ref }_openwrt-rockchip-armv8-friendlyarm_nanopi-r4s-ext4
              path: bin/targets/rockchip/armv8/openwrt-rockchip-armv8-friendlyarm_nanopi-r4s-ext4-sysupgrade.img.gz
          - name: Upload artifacts
            uses: actions/upload-artifact@v3
            with:
              if-no-files-found: ignore
              name: ${{ inputs.openwrt_ref }_openwrt-rockchip-armv8-friendlyelec_nanopi-r5c-ext4
              path: bin/targets/rockchip/armv8/openwrt-rockchip-armv8-friendlyelec_nanopi-r5c-ext4-sysupgrade.img.gz
          - name: Upload artifacts
            uses: actions/upload-artifact@v3
            with:
              if-no-files-found: ignore
              name: ${{ inputs.openwrt_ref }_openwrt-rockchip-armv8-friendlyelec_nanopi-r5s-ext4
              path: bin/targets/rockchip/armv8/openwrt-rockchip-armv8-friendlyelec_nanopi-r5s-ext4-sysupgrade.img.gz
          - name: Upload artifacts
            uses: actions/upload-artifact@v3
            with:
              if-no-files-found: ignore
              name: ${{ inputs.openwrt_ref }_openwrt-rockchip-armv8-friendlyelec_nanopi-r6c-plus-ext4
              path: bin/targets/rockchip/armv8/openwrt-rockchip-armv8-friendlyelec_nanopi-r6c-plus-ext4-sysupgrade.img.gz
          - name: Upload artifacts
            uses: actions/upload-artifact@v3
            with:
              if-no-files-found: ignore
              name: ${{ inputs.openwrt_ref }_openwrt-rockchip-armv8-friendlyelec_nanopi-r6c-ext4
              path: bin/targets/rockchip/armv8/openwrt-rockchip-armv8-friendlyelec_nanopi-r6c-ext4-sysupgrade.img.gz
          - name: Upload artifacts
            uses: actions/upload-artifact@v3
            with:
              if-no-files-found: ignore
              name: ${{ inputs.openwrt_ref }_openwrt-rockchip-armv8-friendlyelec_nanopi-r6s-ext4
              path: bin/targets/rockchip/armv8/openwrt-rockchip-armv8-friendlyelec_nanopi-r6s-ext4-sysupgrade.img.gz
          - name: Upload artifacts
            uses: actions/upload-artifact@v3
            with:
              if-no-files-found: ignore
              name: ${{ inputs.openwrt_ref }_openwrt-rockchip-armv8-pine64_quartz64-a-ext4
              path: bin/targets/rockchip/armv8/openwrt-rockchip-armv8-pine64_quartz64-a-ext4-sysupgrade.img.gz
          - name: Upload artifacts
            uses: actions/upload-artifact@v3
            with:
              if-no-files-found: ignore
              name: ${{ inputs.openwrt_ref }_openwrt-rockchip-armv8-radxa_rock-3a-ext4
              path: bin/targets/rockchip/armv8/openwrt-rockchip-armv8-radxa_rock-3a-ext4-sysupgrade.img.gz
          - name: Upload artifacts
            uses: actions/upload-artifact@v3
            with:
              if-no-files-found: ignore
              name: ${{ inputs.openwrt_ref }_openwrt-rockchip-armv8-radxa_rock-pi-4-ext4
              path: bin/targets/rockchip/armv8/openwrt-rockchip-armv8-radxa_rock-pi-4-ext4-sysupgrade.img.gz
          - name: Upload artifacts
            uses: actions/upload-artifact@v3
            with:
              if-no-files-found: warn
              name: ${{ inputs.openwrt_ref }_openwrt-rockchip-armv8-xunlong_orangepi-5-plus-ext4
              path: bin/targets/rockchip/armv8/openwrt-rockchip-armv8-xunlong_orangepi-5-plus-ext4-sysupgrade.img.gz
