name: Build u-boot for BoughBoot-dev
run-name: Build u-boot for BoughBoot-dev
on:
  workflow_dispatch:
    inputs:
      uboot_gh_repo:
        description: u-boot github repo
        required: true
        default: ArchemedIan/u-boot-rockchip
        type: string
      uboot_ref:
        description: u-boot ref
        required: true
        default: bb
        type: string
      rkbin_ref:
        description: rkbin ref
        required: true
        default: master
        type: string

jobs:
  build:
    name: ${{ matrix.boards.name }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        boards: 
          [
            {
              "name": "rk3588-orangepi-5-plus",
              "config": "orangepi-5-plus-rk3588_defconfig",
            }
          ]

    steps:
      - name: Toolchain
        run: |
          sudo apt-get update
          sudo apt-get install gcc-12 gcc-12-aarch64-linux-gnu python3-pyelftools confget

          sudo ln -sf cpp-12 /usr/bin/cpp
          sudo ln -sf gcc-12 /usr/bin/gcc
          sudo ln -sf gcc-ar-12 /usr/bin/gcc-ar
          sudo ln -sf gcc-nm-12 /usr/bin/gcc-nm
          sudo ln -sf gcc-ranlib-12 /usr/bin/gcc-ranlib
          sudo ln -sf gcov-12 /usr/bin/gcov
          sudo ln -sf gcov-dump-12 /usr/bin/gcov-dump
          sudo ln -sf gcov-tool-12 /usr/bin/gcov-tool

          sudo ln -sf aarch64-linux-gnu-cpp-12 /usr/bin/aarch64-linux-gnu-cpp
          sudo ln -sf aarch64-linux-gnu-gcc-12 /usr/bin/aarch64-linux-gnu-gcc
          sudo ln -sf aarch64-linux-gnu-gcc-ar-12 /usr/bin/aarch64-linux-gnu-gcc-ar
          sudo ln -sf aarch64-linux-gnu-gcc-nm-12 /usr/bin/aarch64-linux-gnu-gcc-nm
          sudo ln -sf aarch64-linux-gnu-gcc-ranlib-12 /usr/bin/aarch64-linux-gnu-gcc-ranlib
          sudo ln -sf aarch64-linux-gnu-gcov-12 /usr/bin/aarch64-linux-gnu-gcov
          sudo ln -sf aarch64-linux-gnu-gcov-dump-12 /usr/bin/aarch64-linux-gnu-gcov-dump
          sudo ln -sf aarch64-linux-gnu-gcov-tool-12 /usr/bin/aarch64-linux-gnu-gcov-tool

      - name: Checkout rkbin - ${{ inputs.rkbin_ref }}
        uses: actions/checkout@v3
        with:
          repository: rockchip-linux/rkbin
          ref: ${{ inputs.rkbin_ref }}
          path: rkbin

      - name: Checkout u-boot - ${{ inputs.uboot_ref }} from ${{ inputs.uboot_gh_repo }}
        uses: actions/checkout@v3
        with:
          repository: ${{ inputs.uboot_gh_repo }}
          ref: ${{ inputs.uboot_ref }}
          path: u-boot

      - name: Build u-boot - ${{ matrix.boards.config }}
        run: |
          export ROCKCHIP_TPL=../rkbin/$(confget -f rkbin/RKBOOT/RK3588MINIALL.ini -s LOADER_OPTION FlashData)
          export BL31=../rkbin/$(confget -f rkbin/RKTRUST/RK3588TRUST.ini -s BL31_OPTION PATH)
          cd u-boot
          make mrproper
          make ${{ matrix.boards.config }}
          make KCFLAGS="-fno-peephole2" CROSS_COMPILE=aarch64-linux-gnu- -j$(nproc)

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.boards.name }}
          path: |
            u-boot/u-boot*
            u-boot/idbloader.img
            u-boot/idbloader-spi.img



-rw-r--r--   1 runner docker  206848 Nov 29 14:27 idbloader-spi.img
-rw-r--r--   1 runner docker  206848 Nov 29 14:27 idbloader.img
-rwxr-xr-x   1 runner docker 8111136 Nov 29 14:27 u-boot
-rw-r--r--   1 runner docker  957552 Nov 29 14:27 u-boot-dtb.bin
-rw-r--r--   1 runner docker  958568 Nov 29 14:27 u-boot-dtb.img
-rwxr-xr-x   1 runner docker  861056 Nov 29 14:27 u-boot-nodtb.bin
-rw-r--r--   1 runner docker 1603072 Nov 29 14:27 u-boot-rockchip-spi.bin
-rw-r--r--   1 runner docker 9565696 Nov 29 14:27 u-boot-rockchip.bin
-rw-r--r--   1 runner docker    5037 Nov 29 14:27 u-boot-spl.dtb.out
-rw-r--r--   1 runner docker  957552 Nov 29 14:27 u-boot.bin
-rw-r--r--   1 runner docker   18168 Nov 29 14:26 u-boot.cfg
-rw-r--r--   1 runner docker   96496 Nov 29 14:27 u-boot.dtb
-rw-r--r--   1 runner docker   97570 Nov 29 14:27 u-boot.dtb.out
-rw-r--r--   1 runner docker  958568 Nov 29 14:27 u-boot.img
-rw-r--r--   1 runner docker 1209856 Nov 29 14:27 u-boot.itb
-rw-r--r--   1 runner docker    1350 Nov 29 14:27 u-boot.lds
-rw-r--r--   1 runner docker 1180187 Nov 29 14:27 u-boot.map
-rwxr-xr-x   1 runner docker 2475668 Nov 29 14:27 u-boot.srec
-rw-r--r--   1 runner docker  318755 Nov 29 14:27 u-boot.sym



